// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import LogoSwiper from "./components/swiper";
import { BsGraphUpArrow } from "react-icons/bs";
import { AiOutlinePound } from "react-icons/ai";
import { IoWalletOutline } from "react-icons/io5";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nescol Utilities",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <main className="bg-white">
          {children}

          {/* Sustainability Section */}
          <section className="bg-white py-12 px-4 sm:px-6 rounded-3xl text-center">
            <h2 className="text-2xl sm:text-3xl font-bold text-gray-800 mb-8">
              Sustainability starts with smarter savings.
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-10 max-w-6xl mx-auto text-left">
              {/* Card 1 */}
              <div className="flex flex-col justify-center items-center gap-8 bg-white p-6 rounded-xl shadow-md">
                <h3 className="font-bold text-lg mb-2">Energy Insights</h3>
                <div className="text-7xl text-black mb-4"><BsGraphUpArrow /></div>
                <p className="text-center max-w-[250px]">
                  Understand your consumption to make informed choices.
                </p>
              </div>

              {/* Card 2 */}
              <div className="flex flex-col justify-center items-center gap-8 bg-white p-6 rounded-xl shadow-md">
                <h3 className="font-bold text-lg mb-2">Pay What’s Fair</h3>
                <div className="text-7xl text-black mb-4"><AiOutlinePound /></div>
                <p className="text-center max-w-[250px]">
                  Pay based on your actual usage—skip random market spikes and inflated rates.
                </p>
              </div>

              {/* Card 3 */}
              <div className="flex flex-col justify-center items-center gap-8 bg-white p-6 rounded-xl shadow-md">
                <h3 className="font-bold text-lg mb-2">Save Smarter</h3>
                <div className="text-7xl text-black mb-4"><IoWalletOutline /></div>
                <p className="text-center max-w-[250px]">
                  Save your money with energy pricing that enhance your lifestyle.
                </p>
              </div>
            </div>
          </section>

          {/* Supplier Logos */}
          <section className="mt-5 mb-5 bg-gray-100">
            <div className="flex items-center justify-center pt-8 pb-4 px-4 text-center">
              <h1 className="text-xl sm:text-2xl font-semibold">
                Trusted suppliers. Reliable service. Just what you deserve.
              </h1>
            </div>
            <LogoSwiper />
          </section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
