import { Geist, Geist_Mono } from "next/font/google";
import LogoSwiper from "./components/swiper"; 
import { FaBolt, FaFireFlameCurved,  FaWifi  } from "react-icons/fa6";
import { IoWalletOutline } from "react-icons/io5";
import { AiOutlinePound } from "react-icons/ai";
import { BsGraphUpArrow } from "react-icons/bs";
import { HiOutlineCurrencyPound } from "react-icons/hi";
import { FaTint } from "react-icons/fa";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nescol Utilities",
  description: "Generated by create next app",
  icons: {
    icons: 'favicon.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <main>{children}</main>
        <section className="bg-white-100 py-12 px-6 rounded-3xl text-center">
  <h2 className="text-3xl font-bold text-gray-800 mb-8">Sustainability starts with smarter savings.</h2>
  
  <div className="grid grid-cols-1 md:grid-cols-3 gap-10 max-w-6xl mx-auto text-left">
    
    <div className="flex flex-col justify-center items-center gap-8 bg-white p-6 rounded-xl shadow-md">
      <h3 className="font-bold text-lg mb-2"> Energy Insights</h3>
      <div className="text-8xl text-black mb-4"><BsGraphUpArrow /></div>
      <p className=" text-center">Understand your consumption to make informed choices.</p>
    </div>

    <div className=" flex flex-col justify-center items-center gap-8 bg-white p-6 rounded-xl shadow-md">
        <h3 className="font-bold text-lg mb-2">Pay What’s Fair</h3>
      <div className="text-8xl text-black  mb-4 "><AiOutlinePound /></div>
      <p className=" text-center">Pay based on your actual usage—skip random market spikes and inflated rates.</p>
    </div>

    <div className=" flex flex-col justify-center items-center gap-8 bg-white p-6 rounded-xl shadow-md">
      <h3 className="font-bold text-lg mb-2">Save Smarter</h3>
      <div className="text-8xl text-black mb-4"><IoWalletOutline /></div> 
      <p className=" text-center">Save your money with energy pricing that enhance your lifestyle</p>
    </div>
    
  </div>
</section>
         <div className="  mt-5 mb-5 bg-gray-100 ">
            <div className=" flex items-center justify-center pt-8 pb-4 ">
              <h1 className=" text-2xl l font-semibold ">Trusted suppliers. Reliable service. Just what you deserve.</h1>
            </div>
           <LogoSwiper/>
          </div>
        <Footer/>
      </body>
    </html>
  );
}
