// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import LogoSwiper from "./components/swiper";
import { BsGraphUpArrow } from "react-icons/bs";
import { AiOutlinePound } from "react-icons/ai";
import { IoWalletOutline } from "react-icons/io5";
import FloatingButton from './components/FloatingButton';
import SustainabilitySection from "./components/SustainabilitySection";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Image from "next/image";
import SuccessAlert from "./components/SuccessAlert";
import TrustpilotWidget from "./components/TrustpilotWidget";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nescol Utilities",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <main className="bg-white">
          {children}

          <SustainabilitySection/>

          <section className="flex flex-col md:flex-row items-center gap-8 max-w-6xl mx-auto py-16 px-4">
            <div className="flex-[1.5] relative h-[350px]">
  <Image
    src="/assets/business1.jpg"
    alt="Business energy"
    fill
    className="rounded-xl object-cover"
  />
</div>


            <div className=" flex-1 text-left">
              <h2 className=" text-2xl font-bold mb-2">
                Simplify your business billing and start saving today with Nescol Utilities.
              </h2>

              <p className="mb-2">
                 Why stay loyal to one supplier when your business deserves better?
              </p>

               <p className="mb-2">
          At Nescol Utilities, we help you manage energy, broadband, and more smarter, not harder.
              </p>

              <p className="mb-2">
          Business contracts are complex, with tailored rates and no cooling-off period. Sticking with one supplier could mean overpaying.
          </p>
        <p>
          We make it easy to compare, customize, and lock in competitive deals that fit your needs. Whether you are a startup or scaling up, we keep your bills efficient, intelligent, and profitable.
        </p>



            </div>
          </section>

          {/* Supplier Logos */}
          <section className="mt-5 mb-5 bg-gray-100">
            <div className="flex items-center justify-center pt-8 pb-4 px-4 text-center">
              <h1 className="text-xl sm:text-2xl font-semibold">
                We connect you with vetted suppliers for reliable service.
              </h1>
            </div>
            <LogoSwiper />
          </section>
        </main>
        <FloatingButton/>
        <Footer />
      </body>
    </html>
  );
}
